[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
