[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "https://w.lucaswinkler.dev/*"
  to = "https://www.lucaswinkler.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ww.lucaswinkler.dev/*"
  to = "https://www.lucaswinkler.dev/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://wwww.lucaswinkler.dev/*"
  to = "https://www.lucaswinkler.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://lucaswinkler.netlify.app/*"
  to = "https://www.lucaswinkler.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
